# Generated by Django 3.0.3 on 2020-07-24 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(1, 'Open'), (2, 'Receive'), (3, 'Transfer'), (4, 'Pay'), (5, 'Calibrate'), (6, 'Close')])),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('last_modify', models.DateTimeField(default=django.utils.timezone.now)),
                ('acct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Acct')),
            ],
        ),
        migrations.CreateModel(
            name='L1_suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='L2_suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('count', models.IntegerField(default=0)),
                ('l1_suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.L1_suggestion')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Acct')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.History')),
            ],
        ),
        migrations.CreateModel(
            name='Receive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.History')),
                ('l2_suggestion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.L2_suggestion')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.History')),
                ('l2_suggestion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.L2_suggestion')),
            ],
        ),
        migrations.CreateModel(
            name='Acct_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='acct',
            name='acct_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Acct_type'),
        ),
    ]
